# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PKW', '0002_auto_20160410_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voivodeship',
            name='relevant_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='votingresult',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
