# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PKW', '0004_voivodeship_nr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['Name']},
        ),
    ]
