# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-06 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PKW', '0006_auto_20160806_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='Type',
            field=models.CharField(default='asd', max_length=20),
            preserve_default=False,
        ),
    ]
