# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 00:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PKW', '0008_district_votes_for_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='last_edit_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
